/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as WorkersRouteImport } from "./routes/workers";
import { Route as NamespaceIdRouteRouteImport } from "./routes/$namespaceId/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as NamespaceIdIndexRouteImport } from "./routes/$namespaceId/index";
import { Route as NamespaceIdWorkflowsRouteRouteImport } from "./routes/$namespaceId/workflows/route";
import { Route as NamespaceIdSchedulesRouteRouteImport } from "./routes/$namespaceId/schedules/route";
import { Route as NamespaceIdWorkflowsIndexRouteImport } from "./routes/$namespaceId/workflows/index";
import { Route as NamespaceIdSchedulesIndexRouteImport } from "./routes/$namespaceId/schedules/index";
import { Route as NamespaceIdWorkflowsIdRouteImport } from "./routes/$namespaceId/workflows/$id";
import { Route as NamespaceIdSchedulesIdRouteImport } from "./routes/$namespaceId/schedules/$id";

const WorkersRoute = WorkersRouteImport.update({
  id: "/workers",
  path: "/workers",
  getParentRoute: () => rootRouteImport,
} as any);
const NamespaceIdRouteRoute = NamespaceIdRouteRouteImport.update({
  id: "/$namespaceId",
  path: "/$namespaceId",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const NamespaceIdIndexRoute = NamespaceIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => NamespaceIdRouteRoute,
} as any);
const NamespaceIdWorkflowsRouteRoute = NamespaceIdWorkflowsRouteRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => NamespaceIdRouteRoute,
} as any);
const NamespaceIdSchedulesRouteRoute = NamespaceIdSchedulesRouteRouteImport.update({
  id: "/schedules",
  path: "/schedules",
  getParentRoute: () => NamespaceIdRouteRoute,
} as any);
const NamespaceIdWorkflowsIndexRoute = NamespaceIdWorkflowsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => NamespaceIdWorkflowsRouteRoute,
} as any);
const NamespaceIdSchedulesIndexRoute = NamespaceIdSchedulesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => NamespaceIdSchedulesRouteRoute,
} as any);
const NamespaceIdWorkflowsIdRoute = NamespaceIdWorkflowsIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => NamespaceIdWorkflowsRouteRoute,
} as any);
const NamespaceIdSchedulesIdRoute = NamespaceIdSchedulesIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => NamespaceIdSchedulesRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$namespaceId": typeof NamespaceIdRouteRouteWithChildren;
  "/workers": typeof WorkersRoute;
  "/$namespaceId/schedules": typeof NamespaceIdSchedulesRouteRouteWithChildren;
  "/$namespaceId/workflows": typeof NamespaceIdWorkflowsRouteRouteWithChildren;
  "/$namespaceId/": typeof NamespaceIdIndexRoute;
  "/$namespaceId/schedules/$id": typeof NamespaceIdSchedulesIdRoute;
  "/$namespaceId/workflows/$id": typeof NamespaceIdWorkflowsIdRoute;
  "/$namespaceId/schedules/": typeof NamespaceIdSchedulesIndexRoute;
  "/$namespaceId/workflows/": typeof NamespaceIdWorkflowsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/workers": typeof WorkersRoute;
  "/$namespaceId": typeof NamespaceIdIndexRoute;
  "/$namespaceId/schedules/$id": typeof NamespaceIdSchedulesIdRoute;
  "/$namespaceId/workflows/$id": typeof NamespaceIdWorkflowsIdRoute;
  "/$namespaceId/schedules": typeof NamespaceIdSchedulesIndexRoute;
  "/$namespaceId/workflows": typeof NamespaceIdWorkflowsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$namespaceId": typeof NamespaceIdRouteRouteWithChildren;
  "/workers": typeof WorkersRoute;
  "/$namespaceId/schedules": typeof NamespaceIdSchedulesRouteRouteWithChildren;
  "/$namespaceId/workflows": typeof NamespaceIdWorkflowsRouteRouteWithChildren;
  "/$namespaceId/": typeof NamespaceIdIndexRoute;
  "/$namespaceId/schedules/$id": typeof NamespaceIdSchedulesIdRoute;
  "/$namespaceId/workflows/$id": typeof NamespaceIdWorkflowsIdRoute;
  "/$namespaceId/schedules/": typeof NamespaceIdSchedulesIndexRoute;
  "/$namespaceId/workflows/": typeof NamespaceIdWorkflowsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$namespaceId"
    | "/workers"
    | "/$namespaceId/schedules"
    | "/$namespaceId/workflows"
    | "/$namespaceId/"
    | "/$namespaceId/schedules/$id"
    | "/$namespaceId/workflows/$id"
    | "/$namespaceId/schedules/"
    | "/$namespaceId/workflows/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/workers"
    | "/$namespaceId"
    | "/$namespaceId/schedules/$id"
    | "/$namespaceId/workflows/$id"
    | "/$namespaceId/schedules"
    | "/$namespaceId/workflows";
  id:
    | "__root__"
    | "/"
    | "/$namespaceId"
    | "/workers"
    | "/$namespaceId/schedules"
    | "/$namespaceId/workflows"
    | "/$namespaceId/"
    | "/$namespaceId/schedules/$id"
    | "/$namespaceId/workflows/$id"
    | "/$namespaceId/schedules/"
    | "/$namespaceId/workflows/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  NamespaceIdRouteRoute: typeof NamespaceIdRouteRouteWithChildren;
  WorkersRoute: typeof WorkersRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workers": {
      id: "/workers";
      path: "/workers";
      fullPath: "/workers";
      preLoaderRoute: typeof WorkersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$namespaceId": {
      id: "/$namespaceId";
      path: "/$namespaceId";
      fullPath: "/$namespaceId";
      preLoaderRoute: typeof NamespaceIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$namespaceId/": {
      id: "/$namespaceId/";
      path: "/";
      fullPath: "/$namespaceId/";
      preLoaderRoute: typeof NamespaceIdIndexRouteImport;
      parentRoute: typeof NamespaceIdRouteRoute;
    };
    "/$namespaceId/workflows": {
      id: "/$namespaceId/workflows";
      path: "/workflows";
      fullPath: "/$namespaceId/workflows";
      preLoaderRoute: typeof NamespaceIdWorkflowsRouteRouteImport;
      parentRoute: typeof NamespaceIdRouteRoute;
    };
    "/$namespaceId/schedules": {
      id: "/$namespaceId/schedules";
      path: "/schedules";
      fullPath: "/$namespaceId/schedules";
      preLoaderRoute: typeof NamespaceIdSchedulesRouteRouteImport;
      parentRoute: typeof NamespaceIdRouteRoute;
    };
    "/$namespaceId/workflows/": {
      id: "/$namespaceId/workflows/";
      path: "/";
      fullPath: "/$namespaceId/workflows/";
      preLoaderRoute: typeof NamespaceIdWorkflowsIndexRouteImport;
      parentRoute: typeof NamespaceIdWorkflowsRouteRoute;
    };
    "/$namespaceId/schedules/": {
      id: "/$namespaceId/schedules/";
      path: "/";
      fullPath: "/$namespaceId/schedules/";
      preLoaderRoute: typeof NamespaceIdSchedulesIndexRouteImport;
      parentRoute: typeof NamespaceIdSchedulesRouteRoute;
    };
    "/$namespaceId/workflows/$id": {
      id: "/$namespaceId/workflows/$id";
      path: "/$id";
      fullPath: "/$namespaceId/workflows/$id";
      preLoaderRoute: typeof NamespaceIdWorkflowsIdRouteImport;
      parentRoute: typeof NamespaceIdWorkflowsRouteRoute;
    };
    "/$namespaceId/schedules/$id": {
      id: "/$namespaceId/schedules/$id";
      path: "/$id";
      fullPath: "/$namespaceId/schedules/$id";
      preLoaderRoute: typeof NamespaceIdSchedulesIdRouteImport;
      parentRoute: typeof NamespaceIdSchedulesRouteRoute;
    };
  }
}

interface NamespaceIdSchedulesRouteRouteChildren {
  NamespaceIdSchedulesIdRoute: typeof NamespaceIdSchedulesIdRoute;
  NamespaceIdSchedulesIndexRoute: typeof NamespaceIdSchedulesIndexRoute;
}

const NamespaceIdSchedulesRouteRouteChildren: NamespaceIdSchedulesRouteRouteChildren = {
  NamespaceIdSchedulesIdRoute: NamespaceIdSchedulesIdRoute,
  NamespaceIdSchedulesIndexRoute: NamespaceIdSchedulesIndexRoute,
};

const NamespaceIdSchedulesRouteRouteWithChildren = NamespaceIdSchedulesRouteRoute._addFileChildren(
  NamespaceIdSchedulesRouteRouteChildren,
);

interface NamespaceIdWorkflowsRouteRouteChildren {
  NamespaceIdWorkflowsIdRoute: typeof NamespaceIdWorkflowsIdRoute;
  NamespaceIdWorkflowsIndexRoute: typeof NamespaceIdWorkflowsIndexRoute;
}

const NamespaceIdWorkflowsRouteRouteChildren: NamespaceIdWorkflowsRouteRouteChildren = {
  NamespaceIdWorkflowsIdRoute: NamespaceIdWorkflowsIdRoute,
  NamespaceIdWorkflowsIndexRoute: NamespaceIdWorkflowsIndexRoute,
};

const NamespaceIdWorkflowsRouteRouteWithChildren = NamespaceIdWorkflowsRouteRoute._addFileChildren(
  NamespaceIdWorkflowsRouteRouteChildren,
);

interface NamespaceIdRouteRouteChildren {
  NamespaceIdSchedulesRouteRoute: typeof NamespaceIdSchedulesRouteRouteWithChildren;
  NamespaceIdWorkflowsRouteRoute: typeof NamespaceIdWorkflowsRouteRouteWithChildren;
  NamespaceIdIndexRoute: typeof NamespaceIdIndexRoute;
}

const NamespaceIdRouteRouteChildren: NamespaceIdRouteRouteChildren = {
  NamespaceIdSchedulesRouteRoute: NamespaceIdSchedulesRouteRouteWithChildren,
  NamespaceIdWorkflowsRouteRoute: NamespaceIdWorkflowsRouteRouteWithChildren,
  NamespaceIdIndexRoute: NamespaceIdIndexRoute,
};

const NamespaceIdRouteRouteWithChildren = NamespaceIdRouteRoute._addFileChildren(
  NamespaceIdRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NamespaceIdRouteRoute: NamespaceIdRouteRouteWithChildren,
  WorkersRoute: WorkersRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
